github:
  description: "Apache Texera Website"
  homepage: "https://texera.apache.org/"
  labels:
    - texera
    - website

staging:
  profile: ~
  whoami:  staging

publish:
  whoami:  main

notifications:
  commits:              commits@texera.apache.org
  issues:               notifications@texera.apache.org
  pullrequests:         notifications@texera.apache.org
  discussions:          notifications@texera.apache.org
  jobs:                 commits@texera.apache.org
