github:
  description: "Apache Texera Website"
  homepage: "https://texera.apache.org/"
  labels:
    - texera
    - website

staging:
  profile: ~
  whoami:  staging
  subdir:  public
 
publish:
  whoami:  main
  subdir:  public
