baseURL = "https://example.docsy.dev/"
title = "Texera"

# Language settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Comment out to disable taxonomies in Docsy
# disableKinds = ["taxonomy"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same length as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Language configuration
[languages]
[languages.en]
languageName = "English"
title = "Texera"
contentDir = "content/en"
weight = 1
[languages.en.params]
title = "Texera"
description = "Apache Texera: interactive, scalable dataflow analytics"
[languages.en.menu]
[[languages.en.menu.main]]
name = "Docs"
url  = "/docs/"
weight = 10

[languages.es]
languageName = "Español"
title = "Texera"
contentDir = "content/es"
weight = 2
[languages.es.params]
title = "Texera"
description = "Apache Texera: flujos de datos interactivos y escalables"
time_format_default = "02-01-2006"
time_format_blog = "2 de enero de 2006"
# Optional: ES menus so the top navbar is populated
[languages.es.menu]
[[languages.es.menu.main]]
name = "Documentación"
url  = "/es/docs/"
weight = 10

[markup]
[markup.goldmark]
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "tango"
# guessSyntax = "true"

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print", "RSS"]

# Everything below this are Site Params
[params]
privacy_policy = "https://www.apache.org/foundation/policies/privacy.html"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/texera-card.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
version_menu = "Releases"

# Version banner config
archived_version = false
version = "0.7.1"
url_latest_version = "https://texera.apache.org"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
# If this site lives in a separate repo, point github_repo there. Otherwise keep it on the main project.
github_repo = "https://github.com/apache/texera-site"
# Related project repo where main code lives
github_project_repo = "https://github.com/apache/texera"

# github_subdir = ""
github_branch = "main"

# Search (comment out to disable)
gcs_engine_id = "d72aa9b2712488cc3"
offlineSearch = false
prism_syntax_highlighting = false

[params.copyright]
authors = "Apache Texera Contributors | © The Apache Software Foundation"
from_year = 2018

# User interface configuration
[params.ui]
breadcrumb_disable = false
navbar_logo = true
navbar_translucent_over_cover_disable = false
sidebar_menu_compact = false
sidebar_search_disable = false

[params.ui.feedback]
enable = true
yes = 'Glad to hear it! Please <a href="https://github.com/apache/texera-site/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/apache/texera-site/issues/new">tell us how we can improve</a>.'

[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links (left side footer & community page)
[[params.links.user]]
name = "User mailing list"
url = "https://incubator.apache.org/projects/texera.html"
icon = "fa fa-envelope"
desc = "Discussion and help from fellow users"
[[params.links.user]]
name = "Announcements"
url = "https://incubator.apache.org/projects/texera.html"
icon = "fa fa-bullhorn"
desc = "ASF-wide release and news announcements"
[[params.links.user]]
name = "GitHub Discussions"
url = "https://github.com/apache/texera/discussions"
icon = "fab fa-github"
desc = "Questions, ideas, and Q&A"

# Developer relevant links (right side footer & community page)
[[params.links.developer]]
name = "GitHub"
url = "https://github.com/apache/texera"
icon = "fab fa-github"
desc = "Development happens here"
[[params.links.developer]]
name = "Dev mailing list"
url = "https://lists.apache.org/list.html?dev@texera.apache.org"
icon = "fa fa-envelope"
desc = "Development discussions"
[[params.links.developer]]
name = "Issues"
url = "https://github.com/apache/texera/issues"
icon = "fa fa-tasks"
desc = "Report bugs and track features"

# hugo module configuration
[module]
# workspace = "docsy.work"
[module.hugoVersion]
extended = true
min = "0.146.0"
[[module.imports]]
path = "github.com/google/docsy"
disable = false
